name: Test and deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          CONTENTFUL_SPACE_IDS: '${{ secrets.CONTENTFUL_SPACE_IDS }}'
          CONTENTFUL_MANAGEMENT_TOKEN: '${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}'
        run: |
          for space_id in ${CONTENTFUL_SPACE_IDS}; do
            node_modules/.bin/contentful config add \
              --active-space-id ${space_id} \
              --active-environment-id master \
              --management-token ${CONTENTFUL_MANAGEMENT_TOKEN}

            node_modules/.bin/contentful extension update --force
          done
